/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster!";
  }

  public static void main(String[] args) {

    System.out.println(new App().getGreeting());

    Monster monster = new Monster("スライム", 3);
    System.out.println(monster.toString());

    Monster monster2 = new Monster(0);
    System.out.println(monster2.toString());

  }
}
